apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bme-raspberry
  labels:
    k8s-app: bme-raspberry
spec:
  selector:
    matchLabels:
      name: bme-raspberry
  template:
    metadata:
      labels:
        name: bme-raspberry
    spec:
      nodeSelector:
        bme-detector: "enabled"
        smarter.nodetype: "raspberrypi4"
      tolerations:
      - key: "smarter.type"
        value: "edge"
        effect: "NoSchedule"
      hostname: bme-raspberry
      containers:
      - name: bme-raspberry
        volumeMounts:
        - mountPath: /dev/gpiomem
          name: gpiomem
        - mountPath: /dev/i2c-1
          name: i2c-1
        - mountPath: /dev/ttyACM0
          name: ttyacm0
        securityContext:
          privileged: true
        imagePullPolicy: Always
        command: ["python"]
        args: ["run.py"]
        image : akihirodive/bme:v1.0
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MQTT_BROKER_HOST
          value: "fluent-bit"
        - name: LOG_LEVEL
          value: "DEBUG"
        ports:
        - containerPort: 2222
          hostPort: 2222
      volumes:
      - name: gpiomem
        hostPath:
          path: /dev/gpiomem
      - name: i2c-1
        hostPath:
          path: /dev/i2c-1
      - name: ttyacm0
        hostPath:
          path: /dev/ttyACM0
      terminationGracePeriodSeconds: 30
